### PR TITLE
Zeyong dev

### PR DESCRIPTION
**Pull request by DANaini13**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

add summary component

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

### CODE REVIEW

**Comment by marissa-hagglund** [comment]
Couple changes: 
1) Please add comments before all functions, blocks of code, and any added classes.
2) What is teh code that was added at the bottom of the ths-component? That should not be there....
3) The router link is also no longer audio-nav, it's audiologist

**Comment by tutuwei** [comment]
Looks good to me

**Review by marissa-hagglund — APPROVED** [review]
Looks ready to merge!

**Review by kaleb2 — APPROVED** [review]
Good

**Pull request merged**
